config/equip_jobs.php
config/equip_location_combinations.php
config/equip_locations.php
config/itemtypes2.php

Signed-off-by: Cydh Ramdh <house.bad@gmail.com>

Some iteminfo updates

---

lang/id_id.php

* Added Bahasa Indonesia 'id_id.php'.
* Special thank to @nanakiwurtz for helping.
Signed-off-by: Cydh Ramdh <house.bad@gmail.com>

Language library update

---

lang/pt_br.php

File with portuguese Brazil translation

Portuguese Brazil translation

---

config/application.php

I need to learn to hit Save before uploading commits..

---

themes/bootstrap/main/navbar.php

Re-Adding bootstrap/main/navbar.php fixes #46

---

config/application.php
lib/Flux.php
lib/functions/discordwebhook.php
modules/account/create.php
modules/mail/index.php
modules/servicedesk/create.php
modules/webcommands/index.php

* New Accounts Registered
* New Support Tickets Submitted
* New Web Commands Submitted
* New Mass-Mail Sent

Add Discord Webhook functionality for various FluxCP functions

---

config/application.php
lib/Flux/PaymentNotifyRequest.php

Paypal doesn't handle 80 port connections.
Switching to SSL.
Also added host list to allow sanbox testing :)

SSL Requirement and allow sandbox servers

---

lib/Flux/Template.php

- Fix 404 link in Map Index and Map View

Fix image link

---

config/application.php
data/npc/PeakNPC.txt
modules/server/status.php
themes/default/server/status.php

* Placed display code into correct array - Fixes #87
* Slight edit to the NPC which should resolve any remaining issues - Fixes #106

Player Peak Issues

---

README.md
doc/user_lang.md

Language file documentation

---

config/application.php
lang/en_us.php
modules/servicedesk/catcontrol.php
modules/servicedesk/create.php
modules/servicedesk/desktop.ini
modules/servicedesk/index.php
modules/servicedesk/staffindex.php
modules/servicedesk/staffsettings.php
modules/servicedesk/staffview.php
modules/servicedesk/staffviewclosed.php
modules/servicedesk/view.php
themes/default/item/iteminfo.php
themes/default/servicedesk/catcontrol.php
themes/default/servicedesk/create.php
themes/default/servicedesk/desktop.ini
themes/default/servicedesk/index.php
themes/default/servicedesk/staffindex.php
themes/default/servicedesk/staffsettings.php
themes/default/servicedesk/staffview.php
themes/default/servicedesk/staffviewclosed.php
themes/default/servicedesk/view.php

* Added ability to give credits to accounts that report bugs to your service desk.
* Cleaned up the structure of the settings page.
* Removed my credits and outdated versioning from SD files.

ServiceDesk Credits & Cleanups

---

config/jobs.php

Added new baby jobs in Job Class Information so that the new baby jobs is displayed under server information

Added expanded baby jobs ID in  Job Class Information

---

data/schemas/logindb/cp_cmspages.20131120161901.sql

Follow up to b9e4496

---

data/npc/DonationNPC.txt

- Just a quick encoding change from iso-8859-1 to UTF-8

UTF-8 Encoding

---

.gitignore

Removed user-related files from .gitignore

---

themes/bootstrap/footer.php

which got accessed before the minified jQuery itself got imported.
I hope I did this right, this is my first time using Github like this.

Theme Bootstrap: Fixed a ReferenceError of jQuery

---

config/application.php
lang/en_us.php
modules/buyingstore/index.php
modules/buyingstore/viewshop.php
themes/default/buyingstore/index.php
themes/default/buyingstore/viewshop.php

Added Buyingstore feature

---

themes/default/monster/view.php

Fix Issue #159
Monster Skill Rate must be /100 first before displayed on web
and Cast Time, Delay must be /1000 first before displayed

Fix Issue #159

---

modules/logdata/char.php
modules/logdata/inter.php

Corrected Inter log database lookup

---

config/access.php
config/application.php
config/feedingtypes.php
lang/en_us.php
modules/logdata/feeding.php
themes/default/logdata/feeding.php

* Default access level same like other logdata, `AccountLevel::ADMIN`

Added Feeding Logdata

---

themes/default/ranking/homunculus.php

* Fixes #205
* Thanks to @Kutikuti

Fixed Homunculus ranking's form action

---

modules/account/edit.php

* Removed undefined variable `$vip_time` variable. It's unused yet as the message says "You will need to login via the client to change the VIP time."
* Thanks to @hendra814

Fixes #207

---

lib/Flux.php
modules/account/create.php
modules/account/login.php

* Fixes #82 
* As found in modules
* login.php
* create.php

Renamed redefinition of $server

---

themes/default/logdata/char.php

CharLogAccountIDLabe Edit to CharLogAccountIDLabel

Fix incorrect terminology

---

themes/default/monster/view.php

* Corrected monster's variable `defense_motion` to `delay_motion`
* Thanks @hendra814

Fixed #202

---

lang/en_us.php
lang/es_es.php
lang/id_id.php
lang/pt_br.php
lib/Flux.php
themes/bootstrap/footer.php
themes/default/footer.php
themes/default/header.php

I have no idea why there is still no [language switch function](https://rathena.org/board/topic/91356-fluxcp-addon-language-switcher/), so here it is now.
http://recordit.co/S1QQtTloLX

Language switcher

---

modules/ranking/mvp.php
themes/default/ranking/mvp.php

* Fixed #215
* Bug occured if logs tables is in different database with mob, char, login database

Fixed MVP Rankings

---

modules/item/add.php
modules/item/copy.php
modules/item/edit.php

Allowed Item modules to use correct db2 tables

---

.editorconfig

[EditorConfig](https://editorconfig.org/) file to set PHP files follow some points from [PSR-1](https://www.php-fig.org/psr/psr-1/) and [PSR-2](https://www.php-fig.org/psr/psr-12)
and other basic file format, `*.json` (will be used later) ~~and `.yml`~~ (the .yml shouldn't be there, unused lol)

Added .editorconfig file to force editor settings

---

config/application.php

https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNSimulator/

Fix Paypal IPN Link

---

.gitignore
lib/functions/discordwebhook.php

Discord webhook requires Content-Type to be set in cURL options

---

lib/Flux/Athena.php

added body reset

---

themes/default/servicedesk/view.php

* Fixed an issue where XSS was possible in the service desk image url inclusion.
There was an issue where persisted XSS was possible through the service desk. this PR should fix this issue. The XSS could be used to either steal a user session or perform other attacks, e.g. using CSRF to steal the other users email.

[Security]

---

modules/vending/viewshop.php
themes/default/character/view.php

Added missed params (random options) of items for vending module.

Random options: fix sql query from vending list

---

README.md

Updated Codacy Badge URL

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Pull Request Template

---

modules/item/iteminfo.php

Fixes #166 and Fixes #162 
This commit is the Gist https://gist.github.com/cydh/f22fcb1920e8c8251c1e1b6614a35811 by @cydh which resolves issues with parsing colors.

Updated methods for itemInfo parsing

---

lib/Flux/Template.php

Fixed error when monster don't have or have not exist AI/Mode.
For example monster #1964: NIGHTMARE

Fixed monsterMode function

---

config/servers.php
lib/Flux.php
lib/Flux/Template.php
modules/item/view.php
modules/monster/view.php
themes/default/monster/view.php

Issue: https://github.com/rathena/FluxCP/issues/277
Added drop rates config:

Added drop rates config

---

index.php

Only overwrite local PHP INI if DebugMode is enabled

---

config/application.php
config/servers.php
lang/en_us.php
lang/es_es.php
lang/pt_br.php
themes/default/account/create.php

Fixes #333 
* Change UseCaptcha to false
* added message explaining about captcha keys

fix: change captcha to false and add disclaimer

---

themes/default/account/view.php

adding reset look button and reset position button for character in account view

account - view reset look/position on character

---

modules/servicedesk/create.php
modules/servicedesk/staffview.php
modules/servicedesk/view.php
themes/default/servicedesk/staffview.php
themes/default/servicedesk/view.php

This pull request fixes an XSS vulnerability in the project's code. The vulnerability was allowing malicious code to be injected into a page and executed in the user's browser, potentially stealing their cookies and accessing administrator accounts.
To fix this vulnerability, it was identified that the `addslashes()` method in PHP was not working correctly. It was changed to the `htmlentities()` method to ensure that the code is protected from XSS attacks.
* Changing `addslashes()` to `htmlentities()`

Fixing xss vulnerability on servicedesk tickets

---

lib/Flux/SessionData.php

* Moved into self function as usage `$session->checkSecurityCode($code, flag)` so can be used in little workaround for other form usage

Separate Security Code check from SessionData::login

---

data/npc/web_commands.txt

Fixes #362 
Modified variables, fixed loop, clears vars for future use.

Updated Web Commands NPC so it doesn't only run once

---

modules/account/view.php
themes/default/guild/view.php

Error in recent commit. #374

---

lib/Flux/Template.php

Fixes #283 
* ThemePath function read files from addons if file not exist in main theme folder.

Allow to read files from addons with themePath function

---

config/application.php
lib/Flux/Template.php

* Fix problem with url to pages from menu when UseCleanUrls enabled.

Fix hardcoded url

---

lib/Flux/LogFile.php

* Add param to open file with the mode (param passed but not is used)

fix pass mode in log file
