config/access.php
Was being able to see the 'txnview' log paypal to any account without being an administrator, because txnview this in the wrong array.
=> Security fix

config/application.php, lib/Flux/PaymentNotifyRequest.php
Checks if payment notify recieved from paypal servers.
Prevent two critical bugs.
Special request to paypal notify with bypass of paypal reciever email
check.
1. Creates executable .php file in payments log folder via
saveDetailsToFile() function.
2. Sending fake completed payment to get unlimited credits.
Hack report example:
https://gist.github.com/S-anasol/9c91d92686bd0e882ee672a394fa1567#file-gistfile1-txt-L45-L48
Highlighted lines is bug execution example.
Bypass paypal email check(receiver_email) and create shell file(txt_id)
with any code inserted into any request variable.
=> [super very critical] RCE and Unlimited Credits PayPal vulnerability.

config/access.php, config/application.php, data/schemas/charmapdb/cp_itemdesc.20170210033400.sql, modules/item/iteminfo.php, modules/item/view.php, themes/default/item/iteminfo.php, themes/default/item/view.php
* Config 'ShowItemDesc' in application.php defaults to false. Change to true in order to use.
* New SQL file `cp_itemdesc` in the charDB schema.
* Tested with itemInfo.lua from https://github.com/zackdreaver/ROenglishRE/ but assuming the format is the same, it should work with files sourced from other locations.
* Regex could possibly do with sharpening up a little.
* Remember to ensure that your PHP post_max_size is large enough to accomodate your file.
* Not the best implementation, but it works.
* Todays regex headache is thanks to @hurtsky for the suggestion.
=> itemInfo parsing

data/schemas/logindb/cp_txnlog.20170221184601.sql
The returned string for "address_status" contains either confirmed (9 chars) or unconfirmed (11 chars)
=> Increased datasize for address_status

lib/Flux/Athena.php
Using the default Stylist resets chars back to hair 1, hcolor 1, cloth 1.
New char defaults to hair 1, hcolor 0, cloth 0.
FluxCP set all to 0, which is no good as hair 1 is the lowest value.
Changed resetLook to mimic new char values. Closes #122.
=> Fixed vanishing heads

config/access.php, config/application.php, config/cashshopcategories.php, lib/Flux/CashShop.php, modules/cashshop/add.php, modules/cashshop/delete.php, modules/cashshop/edit.php, modules/cashshop/index.php, modules/item/pagemenu/view.php, themes/default/cashshop/add.php, themes/default/cashshop/delete.php, themes/default/cashshop/edit.php, themes/default/cashshop/index.php
* Provides admins the ability to manage the in-game CashShop via their website.
* Items can be added to the CashShop by viewing their ItemDB entry and clicking "Add to CashShop".
* Default Tab entries match rAthena's description. However, in-game textures may have text that differs to these names. Edit as you like.
=> CashShop Module

modules/character/view.php
Previously, mob_db and mob_db2 was hardcoded in the sql and is causing the sql statement to be invalid when you're viewing your character information. Added checking for renewal to append "_re" to the mob_db and mob_db2.
=> Doing a checking for renewal db

modules/account/edit.php
Missing `vip_time` column makes it fail to modify the account.
=> Fixed missing vip_time in edit account query

modules/vending/viewshop.php
https://rathena.org/board/topic/116012-fluxcp-undefined-variable-ismine-in-viewshopphp/
=> Fix notice error with viewshop isMine undefined variable

themes/default/css/flux.css
A small issue about the style of table list in `default` theme.
Height of table list include `empty-row`
The reason:
```css
.empty-row {
visibility: hidden;
}
```
`visibility: hidden;` just hidden content of element but keep width, height and position.
I think we should be using `display: none;`
=> Fix style empty-row

modules/account/create.php
now discord webhook will send message even if `RequireEmailConfirm = true`
and add more information so we would know if there is a problem or not when someone register
=> no discord message if 'RequireEmailConfirm' true

lib/Flux/Connection/Statement.php, modules/logdata/login.php
* A quick bulk bindParam for query params
* Added 2nd param in execute function to set auto-bindParam
* Example usage in logdata/login also fix `response` is invalid column, must be `rcode`
because fluxcp codes always set the params before doing prepare statement `$server->connection->getStatement`
=> Added bindParams function

lib/Flux/LoginServer.php
When md5 is active, the " trim($ password) == '' " condition is no longer valid, because even if the password is blank a 32 character code is generated.
=> correct auth validation

lib/Flux/Captcha.php
Added realpath() to find the font
Tested on Windows (PHP 5.4.16 and 7.2.12) and on Ubuntu 18.04 (7.2.12)
=> Captcha not working on PHP 7.2.12 (Windows)

config/application.php, lib/Flux/Template.php
This update dowload monsters and items images from https://www.divine-pride.net if it's not exist.
=> Add Divine-Pride integration (items and monster images)

index.php
Removed the short-lived zend.ze1_compatibility_mode directive.
Has been introduced in PHP 5.0.0, deprecated since PHP 5.3.0
Follow-up to 48caeccbc7a5205425e8b98ed592a2f174eb0dc6
=> PHP 7.4 compatibility update

config/application.php, lib/Flux/PaymentNotifyRequest.php
Sometimes paypal sends notification from an IP address and checks failed, for example:
**[2022-02-20 16:19:20] Received notification from 173.0.81.140 (173.0.81.140)
[2022-02-21 18:42:20] Received notification from 173.0.81.140 (173.0.81.140)** 
[2022-02-20 02:22:03] Received notification from IP (notify.paypal.com)
Not all ip from list return 'notify.paypal.com' by gethostbyaddr function.
This fix should solve the problem.
Ip list from: https://www.paypal.com/fm/smarthelp/article/what-are-the-ip-addresses-for-live-paypal-servers-ts1056
Thanks ScarrBoy, charlieluvsu, Mirage, kianzack, Loki - Badarosk0 and Cookie for reports.
=> Added check for paypal notify by ip range

lib/Flux/Mailer.php
making the template for some languages like Arabic will mess up the encoding
this ensure that mails are sent with UTF-8
i don't know about this but it might be a good idea to add it to flux config.php ?
=> Correct UTF-8 Support for the Mailer Function

.gitignore, index.php, lib/Flux.php, lib/Flux/Config.php
This adds support for an "import config", just like in rathena.
There are technically two ways to do this:
1) Share template files and require the user to copy them for their configs, and add the files to .gitignore
This would work well, but I'm not sure how to do this retroactively without telling owners to make a backup of their config before we delete the file in the commit. If we want this to be a backwards-incompatible change, then I say let's go for it. Another drawback is if a new commit adds a new key to the config, the users' config won't be updated automatically; they would have to do it manually.
2) The OTHER way, the uglier way, is the way in this PR. We load the import files (if they exist), and merge them on top of the base config. This is more backwards-compatible, as we …
=> Add support for importing configs

lib/Flux.php
Fixes #351.
I added a check if baseURI was null, and if not, handle it. This causes an issue where baseURI is empty, because the `if ($string)` check returns false if `$string` is empty. Because users' BaseURI was empty, we never set it to the default `/`, causing this issue.
=> Fix null check for baseuri

index.php, lib/Flux.php, modules/install/index.php, themes/installer/install/index.php
Fixes #65 
* Provides checks for minimum versions of PHP and MySQL.
* Provides checks for PHP Extensions.
* Provides checks for directory permissions.
If any of the checks fail, the "installer password" form does not display.
Otherwise, the installation process may continue.
It's only taken 7 years to close this Issue. Not bad!
=> Added installation requirement checks

modules/servicedesk/staffview.php, themes/default/servicedesk/staffview.php
Fixes #288  .
* Creates a small textbox for a GM to input the number of credits to give the user when closing a Support Ticket.
* Defaults to whatever the value is of config `SDCreditReward`.
* Contains lots of whitespace removal along the way.
=> Given GMs the ability to change Credit value in SD Ticket

themes/default/item/index.php
Fixes #216  .
* Provides the query error on the item_db index page when Debug mode is turned on.
* If there is no query error, the page will still only state "no items found".
=> Display query error in debug mode if no items found

modules/account/create.php
* When captcha is enabled, automatic authorization after registration does not work.
Before it was send "false" as security code and users get error after registration.
=> Fix auto-login after registration when captcha enabled

themes/default/news/add.php, themes/default/news/edit.php, themes/default/pages/add.php, themes/default/pages/edit.php
Fixes #373  .
- Update TinyMCE to 6x
**Changes**
Before:
After:
=> Update TinyMCE to 6x

config/application.php, modules/account/view.php
Fixes #367, Fixes #310
* Adds a config switch in application.php `DisplayCashPoints` that, when `true`, will display the player's CashPoints in account/view.php instead of their Credits.
=> Config to display CashPoints instead of Credits

config/application.php, index.php
Closes #390  .
* Makes use of Discord as a method of alerting admins to page exceptions.
This will not report generic PHP errors, only errors within the application that would throw the dreaded white page of death. I.E:
This change will also continue to send exceptions to Discord on each page load until the issue is resolved. This doesn't happen often enough to be an annoyance if FluxCP is configured correctly.
=> Send Exception to Discord

config/equip_jobs.php
Fixes #371
* Added `'job_acolyte' => 'Acolyte',` to equip_jobs.php
Not sure how we never noticed that.
=> Add Acolyte to equip_jobs

modules/monster/view.php
- Fix the viewing of monster drops not affected by multiplier set on DropRates.
=> Fix Mob View not reflecting Card multiplier DropRate
